name: Release
on:
    push:
        tags:
            - "extension-v*.*.*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 10.30.3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --filter tubesize

            - name: Build release packages
              run: |
                  pnpm --filter tubesize run pack:firefox
                  pnpm --filter tubesize run pack

            - name: Run Tests
              run: pnpm --filter tubesize run test

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      tubesize/dist/tubesize.zip
                      tubesize/dist_firefox/tubesize_firefox.zip
